# Auto-generated by build_tcms_maps.py
# Generated at: 2025-08-17 12:43:04
# Key = name/summary, Value = id (or list of ids if duplicates)
PRODUCTS = {
  "product test": 1,
  "LEND_USER": 2,
  "BO_LEND": 3,
  "MARKETPLACE_USER": 4,
  "MARKETPLACE_ADMIN": 5
}

CATEGORIES = {
  "--default--": [
    1,
    3,
    4,
    5,
    6
  ],
  "category test": 2,
  "FRONTEND": [
    7,
    9,
    11,
    13
  ],
  "BACKEND": [
    8,
    10,
    12,
    14
  ]
}

CATEGORIES_BY_PRODUCT = {
  "1": {
    "--default--": 1,
    "category test": 2
  },
  "2": {
    "--default--": 3,
    "FRONTEND": 9,
    "BACKEND": 10
  },
  "3": {
    "--default--": 4,
    "FRONTEND": 7,
    "BACKEND": 8
  },
  "4": {
    "--default--": 5,
    "FRONTEND": 13,
    "BACKEND": 14
  },
  "5": {
    "--default--": 6,
    "FRONTEND": 11,
    "BACKEND": 12
  }
}

TEST_CASES = {
  "تست ساخت تست کیس از طریق API": 1,
  "تست لاگین جابینجا": 2,
  "test_get_primary_info_registration_personal": 3,
  "test_create_primary_info_registration_personal_befor_sabtAhval": 4,
  "test_incorrect_nationalCode": 5,
  "test_incorrect_nationalCode_and_birthDate": 6,
  "test_incorrect_birthDate": 7,
  "test_correct_info": 8,
  "test_create_primary_info_registration_personal": 9,
  "test_change_birthdate": 10,
  "test_duplicate_loan_request": 11,
  "test_credit_rank_data": 12,
  "test_complete_credit_rank_step": 13,
  "test_get_loan_data": 14,
  "test_loan_config": 15,
  "test_code_generator": 16,
  "test_loan_data_correct_period": 17,
  "test_loan_data_incorrect_period": 18,
  "test_partial_upload_identity": 19,
  "test_complete_identity_step": 20,
  "test_get_residence_data": 21,
  "test_partial_upload_residence": 22,
  "test_complete_residence_step": 23,
  "test_get_occupation_data": 24,
  "test_partial_upload_occupation": 25,
  "test_complete_occupation_step": 26,
  "test_get_branch_step_data": 27,
  "test_complete_branch_step": 28,
  "test_validate_incorrect_code": 29,
  "test_validate_correct_code": 30,
  "test_complete_primary_info_registration_personal": 31
}

TEST_PLANS = {
  "LEND_USER_BACKEND": 2,
  "LEND_USER_ASSURANCE_BACKEND": 3,
  "test plan test": 1
}

TEST_RUNS = {
  "test runner": [
    1,
    2,
    6
  ],
  "ffff": 3,
  "صثبثصب": 4,
  "test": 5,
  "تست ران شماره 1": 7,
  "test run": 8,
  "test jobinja login": 9,
  "test jobinja login1": 10,
  "test jobinja login2": 11,
  "test jobinja login3": 12,
  "test jobinja login4": 13,
  "test jobinja login 2025-08-16": 14,
  "test_lend_loan_flow_from_zero 2025-08-16 15:13": 15,
  "test_lend_loan_flow_from_zero 2025-08-16 15:14": 16,
  "test_lend_loan_flow_from_zero 2025-08-16 15:29": 17,
  "test_lend_loan_flow_from_zero 2025-08-16 15:31": 18,
  "test_lend_loan_flow_from_zero 2025-08-16 15:32": 19,
  "test_lend_loan_flow_from_zero 2025-08-16 16:10": 20,
  "test_lend_loan_flow_from_zero 2025-08-16 16:26": 21,
  "test_lend_loan_flow_from_zero 2025-08-16 16:42": 22,
  "test_lend_loan_flow_from_zero 2025-08-16 16:44": 23,
  "test_lend_loan_flow_from_zero 2025-08-16 16:45": 24,
  "test_lend_loan_flow_from_zero 2025-08-17 10:24": 25
}

PRIORITIES = {
  "P1": 1,
  "P2": 2,
  "P3": 3,
  "P4": 4,
  "P5": 5
}

TEST_CASE_STATUSES = {
  "PROPOSED": 1,
  "CONFIRMED": 2,
  "DISABLED": 3,
  "NEED_UPDATE": 4
}

TEST_EXECUTION_STATUSES = {
  "IDLE": 1,
  "RUNNING": 2,
  "PAUSED": 3,
  "PASSED": 4,
  "FAILED": 5,
  "BLOCKED": 6,
  "ERROR": 7,
  "WAIVED": 8
}

USERS = {
  "dgstack": 1
}

COMPONENTS = {}

VERSIONS = {
  "unspecified": [
    3,
    2,
    5,
    4,
    1
  ]
}

BUILDS = {
  "unspecified": [
    1,
    2,
    3,
    4,
    5
  ],
  "V1": 6
}

BUILDS_BY_PRODUCT = {
  "1": {
    "unspecified": 1,
    "V1": 6
  },
  "2": {
    "unspecified": 2
  },
  "3": {
    "unspecified": 3
  },
  "4": {
    "unspecified": 4
  },
  "5": {
    "unspecified": 5
  }
}

EXECUTION_STATUSES = {
  "IDLE": 1,
  "RUNNING": 2,
  "PAUSED": 3,
  "PASSED": 4,
  "FAILED": 5,
  "BLOCKED": 6,
  "ERROR": 7,
  "WAIVED": 8
}

