# Auto-generated by build_tcms_maps.py
# Generated at: 2025-08-19 14:45:27
# Key = name/summary, Value = id (or list of ids if duplicates)
PRODUCTS = {
  "LEND_USER": 2,
  "BO_LEND": 3,
  "MARKETPLACE_USER": 4,
  "MARKETPLACE_ADMIN": 5
}

CATEGORIES = {
  "FRONTEND": [
    7,
    9,
    11,
    13
  ],
  "BACKEND": [
    8,
    10,
    12,
    14
  ]
}

CATEGORIES_BY_PRODUCT = {
  "3": {
    "FRONTEND": 7,
    "BACKEND": 8
  },
  "2": {
    "FRONTEND": 9,
    "BACKEND": 10
  },
  "5": {
    "FRONTEND": 11,
    "BACKEND": 12
  },
  "4": {
    "FRONTEND": 13,
    "BACKEND": 14
  }
}

TEST_CASES = {
  "test_get_primary_info_registration_personal": 3,
  "test_create_primary_info_registration_personal_befor_sabtAhval": 4,
  "test_incorrect_nationalCode": 5,
  "test_incorrect_nationalCode_and_birthDate": 6,
  "test_incorrect_birthDate": 7,
  "test_correct_info": 8,
  "test_create_primary_info_registration_personal": 9,
  "test_change_birthdate": 10,
  "test_duplicate_loan_request": 11,
  "test_credit_rank_data": 12,
  "test_complete_credit_rank_step": 13,
  "test_get_loan_data": 14,
  "test_loan_config": 15,
  "test_code_generator": 16,
  "test_loan_data_correct_period": 17,
  "test_loan_data_incorrect_period": 18,
  "test_partial_upload_identity": 19,
  "test_complete_identity_step": 20,
  "test_get_residence_data": 21,
  "test_partial_upload_residence": 22,
  "test_complete_residence_step": 23,
  "test_get_occupation_data": 24,
  "test_partial_upload_occupation": 25,
  "test_complete_occupation_step": 26,
  "test_get_branch_step_data": 27,
  "test_complete_branch_step": 28,
  "test_validate_incorrect_code": 29,
  "test_validate_correct_code": 30,
  "test_complete_primary_info_registration_personal": 31,
  "test_send_otp_first_time": 32,
  "test_send_otp_second_time": 33,
  "test_send_otp_third_time": 34,
  "test_login_correct_otp": 35,
  "test_login_incorrect_otp": 36
}

TEST_PLANS = {
  "LEND_USER_BACKEND": 2,
  "LEND_USER_ASSURANCE_BACKEND": 3,
  "LEND_LOGIN_BACKEND": 4
}

TEST_RUNS = {}

PRIORITIES = {
  "Critical": 1,
  "High": 2,
  "Low-Impact": 4,
  "Medium": 3,
  "Trivial": 5
}

TEST_CASE_STATUSES = {
  "PROPOSED": 1,
  "CONFIRMED": 2,
  "DISABLED": 3,
  "NEED_UPDATE": 4
}

TEST_EXECUTION_STATUSES = {
  "IDLE": 1,
  "RUNNING": 2,
  "PAUSED": 3,
  "PASSED": 4,
  "FAILED": 5,
  "BLOCKED": 6,
  "ERROR": 7,
  "WAIVED": 8
}

USERS = {
  "dgstack": 1
}

COMPONENTS = {}

VERSIONS = {
  "unspecified": [
    3,
    2,
    5,
    4
  ]
}

BUILDS = {
  "unspecified": [
    2,
    3,
    4,
    5
  ]
}

BUILDS_BY_PRODUCT = {
  "2": {
    "unspecified": 2
  },
  "3": {
    "unspecified": 3
  },
  "4": {
    "unspecified": 4
  },
  "5": {
    "unspecified": 5
  }
}

EXECUTION_STATUSES = {
  "IDLE": 1,
  "RUNNING": 2,
  "PAUSED": 3,
  "PASSED": 4,
  "FAILED": 5,
  "BLOCKED": 6,
  "ERROR": 7,
  "WAIVED": 8
}

